version: '3'

services:
  postgres:
    image: postgres:10-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=gistcatch
      - POSTGRES_PASSWORD=secret
    ports:
      - "15432:5432"
    # volumes:
    #   - postgres:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    depends_on:
      - postgres
    ports:
      - "8080:3000"
    # volumes:
    #   - .:/gistcatch

# volumes:
#   web:
#   postgres:
